#
# https://github.com/P3TERX/Actions-OpenWrt
#
# æ–‡ä»¶ï¼š.github/workflows/openwrt-bulder.yml
# æè¿°ï¼šä½¿ç”¨ GitHub Actions æ„å»º OpenWrt
#
# ç‰ˆæƒæ‰€æœ‰ï¼ˆcï¼‰2019-2024 P3TERX <https://p3terx.com>
#
# è¿™æ˜¯è‡ªç”±è½¯ä»¶ï¼Œæ ¹æ® MIT è®¸å¯è¯è¿›è¡Œè®¸å¯ã€‚
# æœ‰å…³æ›´å¤šä¿¡æ¯ï¼Œè¯·å‚è§ /LICENSEã€‚
#

name: OpenWrt immortalwrt Builder  # å·¥ä½œæµåç§°

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt  # ä»“åº“ URL
  REPO_BRANCH: master  # ä»“åº“åˆ†æ”¯
  FEEDS_CONF: feeds.conf.default  # è‡ªå®šä¹‰ feeds é…ç½®æ–‡ä»¶
  CONFIG_FILE: .config  # é…ç½®æ–‡ä»¶
  DIY_P1_SH: diy-part1.sh  # è‡ªå®šä¹‰è„šæœ¬1
  DIY_P2_SH: diy-part2.sh  # è‡ªå®šä¹‰è„šæœ¬2
  UPLOAD_BIN_DIR: false  # æ˜¯å¦ä¸Šä¼  bin ç›®å½•
  UPLOAD_FIRMWARE: true  # æ˜¯å¦ä¸Šä¼ å›ºä»¶
  UPLOAD_RELEASE: true  # æ˜¯å¦ä¸Šä¼ å‘å¸ƒ
  TZ: Asia/Shanghai  # æ—¶åŒº

jobs:
  build:
    runs-on: ubuntu-22.04  # ä½¿ç”¨çš„æ“ä½œç³»ç»Ÿç‰ˆæœ¬

    steps:
    - name: Checkout  # æ­¥éª¤åç§°
      uses: actions/checkout@main  # ä½¿ç”¨çš„åŠ¨ä½œ

    - name: Initialization environment  # åˆå§‹åŒ–ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive  # éäº¤äº’å¼å‰ç«¯
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL  # åˆ é™¤æ—§æ–‡ä»¶
        sudo docker image prune --all --force  # æ¸…ç† Docker é•œåƒ
        sudo -E apt-get -qq update  # æ›´æ–°è½¯ä»¶åŒ…åˆ—è¡¨
        sudo -E apt-get -qq install ...  # å®‰è£…æ‰€éœ€è½¯ä»¶åŒ…
        sudo timedatectl set-timezone "$TZ"  # è®¾ç½®æ—¶åŒº
        sudo mkdir -p /workdir  # åˆ›å»ºå·¥ä½œç›®å½•
        sudo chown $USER:$GROUPS /workdir  # æ›´æ”¹å·¥ä½œç›®å½•çš„æ‰€æœ‰è€…

    - name: Clone source code  # å…‹éš†æºä»£ç 
      working-directory: /workdir  # å·¥ä½œç›®å½•
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt  # å…‹éš†ä»“åº“
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load custom feeds  # åŠ è½½è‡ªå®šä¹‰ feeds
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update feeds  # æ›´æ–° feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds  # å®‰è£… feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration  # åŠ è½½è‡ªå®šä¹‰é…ç½®
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Download package  # ä¸‹è½½è½¯ä»¶åŒ…
      id: package
      run: |
        cd openwrt
        make defconfig
        for i in {1..3}; do make download -j8 && break || sleep 5; done
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware  # ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) V=s || make -j1 V=s || make -j1 V=s V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage  # æ£€æŸ¥ç©ºé—´ä½¿ç”¨æƒ…å†µ
      if: (!cancelled())
      run: df -hT

    - name: Upload bin directory  # ä¸Šä¼  bin ç›®å½•
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Organize files  # æ•´ç†æ–‡ä»¶
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory  # ä¸Šä¼ å›ºä»¶ç›®å½•
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_immortalwrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag  # ç”Ÿæˆå‘å¸ƒæ ‡ç­¾
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        [ ${UPLOAD_GOFILE} = true && ${{ steps.gofile.outputs.url }} ] && echo "ğŸ”— [GoFile](${{ steps.gofile.outputs.url }})" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release  # ä¸Šä¼ å›ºä»¶åˆ°å‘å¸ƒ
      uses: softprops/action-gh-release@
